### ISSUE TITLE
Implement resolvePath() function for resolving a hashed asset path

### ISSUE THREAD

**Issue by espen42** [enonic/lib-static#24]
Probably not in this lib, but worth mentioning and using together:

To save huge complexity (detecting at buildtime what the output and unpredictable hash will be and hooking those references up to output), there should be a function that can resolve a fingerprinted asset filename at XP runtime: 

`resolvePath(globPath, root)`

For example, if a fingerprinted asset _bundle.92d34fd72.js_ is built into _/static_, then `resolvePath('bundle.*.js', 'static')` will look for matching files within _/static_ and return the string `"bundle.92d34fd72.js"`.

We can always later add the functionality that the globPath argument can also be a regex pattern.

`resolvePath` should **never** be part of an asset-serving endpoint service - i.e. it should not be possible to send a glob to the server and get a file response. Instead, it’s meant to be used in controllers to fetch the name of a required asset, e.g:

```
pageContributions: <script src="\${libStaticEndpoint}/\${resolvePath('bundle.*.js', 'static')}">
```

`resolvePath` can/should be part of a different library. Can be its own library (‘lib-resolvepath’?) or part of some other general-purpose lib, for example lib-util.

In dev mode, `resolvePath?` will often find more than one match and select the most recently updated one (and should log it at least once if that’s the case). In prod mode, it should throw an error if more than one is found, and if only one is found, cache it internally.

**Comment by rymsha** [comment]
If there is no need to use resolvePath without lib-static, It probably should be a part of lib-static

**Comment by ComLock** [comment]
Resolving paths made by buildsystems, should be implemented in the consumer application, not lib-static.
