### ISSUE TITLE
An index.html file in the static folder should be hosted on the root of the service

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-static#363]

**Comment by rymsha** [comment]
There are two use-cases for lib-static
1. static content (.js, .css, ...) - we don't want special handling of html files, redirection, or directory-index.
2. static website - we DO want redirection and directory-index

Inspiration:
https://httpd.apache.org/docs/trunk/mod/mod_dir.html

**Comment by ComLock** [comment]
New spec implemented
