### ISSUE TITLE
Security check. Path traversal

### ISSUE THREAD

**Issue by rymsha** [enonic/lib-static#42]
Test for https://owasp.org/www-community/attacks/Path_Traversal prevention

**Comment by espen42** [comment]
Reminder in case this is relevant here too: https://github.com/enonic/lib-static/issues/77#issuecomment-885006628

**Comment by rymsha** [comment]
lib-static cannot fully guard against it. XP can mitigate issues https://github.com/enonic/xp/issues/8981
