### ISSUE TITLE
`.exists()` returns true for directories in XP prod runmode

### ISSUE THREAD

**Issue by espen42** [enonic/lib-static#63]
In XP prod run mode, `.exists()` returns `true` for files as it should, but also for directories whose name don't end with a slash - as it shouldn't. This keeps the redirect/index fallback feature from working in prod mode.

Likely cause: in IoService in **dev mode**, [url.getProtocol()](https://github.com/enonic/lib-static/blob/a7719c8440128d6e35398a8019751a9468a43971/src/main/java/lib/enonic/libStatic/IoService.java#L109) returns `"file"` for both directories and files. Then, `Files.isDirectory( Path.of( url.toURI())` can be used to determine if a url points to a directory, and return false. 

In **prod mode** however, `url.getProtocol()` returns `"bundle"` for both files and directories, and this causes `.exists()` to return `true` in both cases.

**Comment by espen42** [comment]
This seems to be a bug in the fix #58 .

**Comment by rymsha** [comment]
This is due to this bug https://issues.apache.org/jira/browse/FELIX-6294

**Comment by rymsha** [comment]
issue in XP https://github.com/enonic/xp/issues/8753
